//
//  MockAIService.swift
//  AiChat
//
//  Created by Sathya Kumar on 30/06/26.
//

import Foundation

struct MockAIService: AIService {
    func generateImage(input: String) async throws -> String {
        try await Task.sleep(for: .seconds(2))
        return Constants.randomImage
    }

    func generateText(input: String) async throws -> String {
        try await Task.sleep(for: .seconds(1))
        return "This is a mock AI response to: \(input). In production, this would be generated by Pollinations AI."
    }

    func generateTextWithContext(messages: [AIChatModel], systemPrompt: String?) async throws -> String {
        try await Task.sleep(for: .seconds(1))
        let lastMessage = messages.last?.message ?? "no message"
        return "Mock AI response with context to: \(lastMessage)"
    }
}
